// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bech32ibc/v1beta1/gov.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// UpdateHrpIBCRecordProposal is a gov Content type for adding a new record
// between a bech32 prefix and IBC (port, channel) for fungible and non-fungible tokens.
// It can be used to add a new record to the set. It can also be.
// used to update the IBC channel to associate with a specific denom. If both channels
// are set to "", it will remove the record from the set.
type UpdateHrpIbcChannelProposal struct {
	Title                 string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty" yaml:"title"`
	Description           string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty" yaml:"description"`
	Hrp                   string `protobuf:"bytes,3,opt,name=hrp,proto3" json:"hrp,omitempty" yaml:"hrp"`
	FungibleSourceChannel string `protobuf:"bytes,4,opt,name=fungible_source_channel,json=fungibleSourceChannel,proto3" json:"fungible_source_channel,omitempty" yaml:" fungible_source_channel"`
	NftSourceChannel      string `protobuf:"bytes,5,opt,name=nft_source_channel,json=nftSourceChannel,proto3" json:"nft_source_channel,omitempty" yaml:"nft_source_channel"`
}

func (m *UpdateHrpIbcChannelProposal) Reset()      { *m = UpdateHrpIbcChannelProposal{} }
func (*UpdateHrpIbcChannelProposal) ProtoMessage() {}
func (*UpdateHrpIbcChannelProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f7c8abba2b4a209, []int{0}
}
func (m *UpdateHrpIbcChannelProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateHrpIbcChannelProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateHrpIbcChannelProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdateHrpIbcChannelProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateHrpIbcChannelProposal.Merge(m, src)
}
func (m *UpdateHrpIbcChannelProposal) XXX_Size() int {
	return m.Size()
}
func (m *UpdateHrpIbcChannelProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateHrpIbcChannelProposal.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateHrpIbcChannelProposal proto.InternalMessageInfo

func init() {
	proto.RegisterType((*UpdateHrpIbcChannelProposal)(nil), "bech32ibc.bech32ibc.v1beta1.UpdateHrpIbcChannelProposal")
}

func init() { proto.RegisterFile("bech32ibc/v1beta1/gov.proto", fileDescriptor_8f7c8abba2b4a209) }

var fileDescriptor_8f7c8abba2b4a209 = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x3d, 0x8b, 0xdb, 0x30,
	0x18, 0xc7, 0xed, 0xa4, 0x29, 0x54, 0x0d, 0x25, 0x88, 0xbe, 0xb8, 0x09, 0xb5, 0x82, 0x0b, 0xa5,
	0x4b, 0x22, 0x92, 0x2c, 0x25, 0x63, 0xba, 0xb4, 0xb4, 0x43, 0x71, 0xe9, 0xd2, 0x0e, 0x41, 0x72,
	0xe4, 0x17, 0x70, 0x2c, 0x21, 0xcb, 0xa1, 0xf9, 0x06, 0x1d, 0x3b, 0xde, 0x98, 0x8f, 0x73, 0x63,
	0xc6, 0xbb, 0xc5, 0x1c, 0xc9, 0x72, 0xb3, 0x3f, 0xc1, 0x61, 0x29, 0x47, 0x72, 0x77, 0xdc, 0xf6,
	0xd8, 0xbf, 0xdf, 0xff, 0x8f, 0xc4, 0x23, 0xd0, 0xa3, 0x2c, 0x88, 0x27, 0xe3, 0x84, 0x06, 0x78,
	0x35, 0xa2, 0x4c, 0x91, 0x11, 0x8e, 0xf8, 0x6a, 0x28, 0x24, 0x57, 0x1c, 0x1e, 0xe1, 0xf0, 0x38,
	0x1d, 0xb4, 0xee, 0xcb, 0x88, 0x47, 0x5c, 0x7b, 0xb8, 0x9e, 0x4c, 0xa4, 0xeb, 0x46, 0x9c, 0x47,
	0x29, 0xc3, 0xfa, 0x8b, 0x16, 0x21, 0x5e, 0x14, 0x92, 0xa8, 0x84, 0x67, 0x86, 0x7b, 0x97, 0x0d,
	0xd0, 0xfb, 0x25, 0x16, 0x44, 0xb1, 0x2f, 0x52, 0x7c, 0xa5, 0xc1, 0xe7, 0x98, 0x64, 0x19, 0x4b,
	0x7f, 0x48, 0x2e, 0x78, 0x4e, 0x52, 0xf8, 0x01, 0xb4, 0x54, 0xa2, 0x52, 0xe6, 0xd8, 0x7d, 0xfb,
	0xe3, 0xb3, 0x59, 0xa7, 0x2a, 0x51, 0x7b, 0x4d, 0x96, 0xe9, 0xd4, 0xd3, 0xbf, 0x3d, 0xdf, 0x60,
	0xf8, 0x09, 0x3c, 0x5f, 0xb0, 0x3c, 0x90, 0x89, 0xa8, 0xcb, 0x9d, 0x86, 0xb6, 0x5f, 0x57, 0x25,
	0x82, 0xc6, 0x3e, 0x81, 0x9e, 0x7f, 0xaa, 0xc2, 0x3e, 0x68, 0xc6, 0x52, 0x38, 0x4d, 0x9d, 0x78,
	0x51, 0x95, 0x08, 0x98, 0x44, 0x2c, 0x85, 0xe7, 0xd7, 0x08, 0xfe, 0x01, 0x6f, 0xc2, 0x22, 0x8b,
	0x12, 0x9a, 0xb2, 0x79, 0xce, 0x0b, 0x19, 0xb0, 0x79, 0x60, 0x8e, 0xe9, 0x3c, 0xd1, 0xa9, 0xf7,
	0x55, 0x89, 0x90, 0x49, 0xf5, 0x1f, 0x31, 0x3d, 0xff, 0xd5, 0x2d, 0xf9, 0xa9, 0xc1, 0xe1, 0xa2,
	0xf0, 0x1b, 0x80, 0x59, 0xa8, 0xee, 0xf7, 0xb6, 0x74, 0xef, 0xbb, 0xaa, 0x44, 0x6f, 0x4d, 0xef,
	0x43, 0xc7, 0xf3, 0x3b, 0x59, 0xa8, 0xee, 0x94, 0x4d, 0xdb, 0xff, 0x36, 0xc8, 0x3a, 0xdb, 0x20,
	0xeb, 0x7a, 0x83, 0xec, 0xd9, 0xf7, 0xf3, 0x9d, 0x6b, 0x6f, 0x77, 0xae, 0x7d, 0xb5, 0x73, 0xed,
	0xff, 0x7b, 0xd7, 0xda, 0xee, 0x5d, 0xeb, 0x62, 0xef, 0x5a, 0xbf, 0xc7, 0x51, 0xa2, 0xe2, 0x82,
	0x0e, 0x03, 0xbe, 0xc4, 0x24, 0x55, 0x31, 0x23, 0x83, 0x8c, 0x29, 0x6c, 0x96, 0x3a, 0xa8, 0x97,
	0xff, 0x17, 0x1f, 0x1f, 0x82, 0x5a, 0x0b, 0x96, 0xd3, 0xa7, 0x7a, 0x61, 0x93, 0x9b, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x4a, 0x9f, 0xea, 0xa7, 0x22, 0x02, 0x00, 0x00,
}

func (this *UpdateHrpIbcChannelProposal) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpdateHrpIbcChannelProposal)
	if !ok {
		that2, ok := that.(UpdateHrpIbcChannelProposal)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Title != that1.Title {
		return false
	}
	if this.Description != that1.Description {
		return false
	}
	if this.Hrp != that1.Hrp {
		return false
	}
	if this.FungibleSourceChannel != that1.FungibleSourceChannel {
		return false
	}
	if this.NftSourceChannel != that1.NftSourceChannel {
		return false
	}
	return true
}
func (m *UpdateHrpIbcChannelProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateHrpIbcChannelProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UpdateHrpIbcChannelProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NftSourceChannel) > 0 {
		i -= len(m.NftSourceChannel)
		copy(dAtA[i:], m.NftSourceChannel)
		i = encodeVarintGov(dAtA, i, uint64(len(m.NftSourceChannel)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.FungibleSourceChannel) > 0 {
		i -= len(m.FungibleSourceChannel)
		copy(dAtA[i:], m.FungibleSourceChannel)
		i = encodeVarintGov(dAtA, i, uint64(len(m.FungibleSourceChannel)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Hrp) > 0 {
		i -= len(m.Hrp)
		copy(dAtA[i:], m.Hrp)
		i = encodeVarintGov(dAtA, i, uint64(len(m.Hrp)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintGov(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintGov(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGov(dAtA []byte, offset int, v uint64) int {
	offset -= sovGov(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *UpdateHrpIbcChannelProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovGov(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovGov(uint64(l))
	}
	l = len(m.Hrp)
	if l > 0 {
		n += 1 + l + sovGov(uint64(l))
	}
	l = len(m.FungibleSourceChannel)
	if l > 0 {
		n += 1 + l + sovGov(uint64(l))
	}
	l = len(m.NftSourceChannel)
	if l > 0 {
		n += 1 + l + sovGov(uint64(l))
	}
	return n
}

func sovGov(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGov(x uint64) (n int) {
	return sovGov(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UpdateHrpIbcChannelProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGov
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateHrpIbcChannelProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateHrpIbcChannelProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hrp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hrp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FungibleSourceChannel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FungibleSourceChannel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftSourceChannel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGov
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGov
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGov
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftSourceChannel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGov(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGov
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGov(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGov
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGov
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGov
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGov
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGov
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGov
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGov        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGov          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGov = fmt.Errorf("proto: unexpected end of group")
)
